version: '3'

services:
  xteve-channel-alerts:
    image: celsian/xteve-channel-alerts:latest
    container_name: xteve-channel-alerts
    environment:
      - XTEVE_URL=http://your-xteve-server:34400/m3u/xteve.m3u
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/your-webhook-id/your-webhook-token
      - CRON_SCHEDULE=0 4 * * *  # Default: Run daily at 4 AM
    volumes:
      - ./data:/app/data  # Single volume with organized subdirectories: data/logs and data/m3us
    restart: always
